In [1]:
import numpy as np

In [2]:
benimListem = [20,30,40]

In [3]:
type(benimListem)

list

In [4]:
np.array(benimListem)

array([20, 30, 40])

In [5]:
matrixListesi = [[10,20,30],[20,30,40],[30,40,50]]

In [6]:
matrixListesi

[[10, 20, 30], [20, 30, 40], [30, 40, 50]]

In [7]:
np.array(matrixListesi)

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

In [8]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [11]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [14]:
np.ones((9,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [15]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [16]:
np.linspace(0,20,6)

array([ 0.,  4.,  8., 12., 16., 20.])

In [17]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [21]:
np.random.randn()

-0.603388827741527

In [22]:
np.random.randn(4)

array([0.15321309, 1.07190283, 0.87694806, 0.46734505])

In [24]:
np.random.randn(3,3)

array([[-0.26963376,  0.32898136,  0.38837438],
       [-1.01100196,  0.51058874, -1.7191092 ],
       [-1.7390567 , -1.47796703, -0.31334768]])

In [25]:
np.random.randint(1,10)

8

In [26]:
np.random.randint(1,10,5)

array([5, 1, 4, 2, 2])

In [27]:
benimNumpyDizim = np.arange(30)

In [28]:
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [29]:
benimNumpyDizim2 = np.random.randint(1,100,30)

In [30]:
benimNumpyDizim2

array([ 8, 24, 38, 26, 95, 95, 69, 96,  5, 17, 83, 31, 35, 75, 94, 44, 92,
       42, 85, 72, 35, 93, 89, 91, 11, 66, 81, 76, 82, 75])

In [31]:
benimNumpyDizim.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [32]:
benimNumpyDizim.max()

29

In [33]:
benimNumpyDizim2.max()

96

In [34]:
benimNumpyDizim2.argmax()

7