In [2]:
import numpy as np

In [3]:
benimDizim = np.arange(0,15)

In [4]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
benimDizim[5]

5

In [7]:
benimDizim[3:5]

array([3, 4])

In [9]:
benimDizim[3:8] = -5

In [10]:
benimDizim

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [11]:
baskaDizi = np.arange(0,24)

In [12]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [14]:
slicingDizisi = baskaDizi[4:9]

In [16]:
slicingDizisi

array([4, 5, 6, 7, 8])

In [17]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [18]:
type(slicingDizisi)

numpy.ndarray

In [19]:
slicingDizisi[:]=100

In [20]:
slicingDizisi

array([100, 100, 100, 100, 100])

In [21]:
baskaDizi

array([  0,   1,   2,   3, 100, 100, 100, 100, 100,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [25]:
ornekDizi = np.arange(0,24)

In [26]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [27]:
ornekDiziKopyasi= ornekDizi.copy()

In [28]:
ornekDiziKopyasi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
ornekDiziKopyasiSlicing = ornekDiziKopyasi