In [1]:
import numpy as np

In [2]:
##matrix

In [3]:
benimListem = [[10,20,30],[20,30,40],[40,50,60]]

In [4]:
benimMatrixDizim = np.array(benimListem)

In [5]:
benimMatrixDizim

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

In [6]:
benimMatrixDizim[0]

array([10, 20, 30])

In [7]:
benimMatrixDizim[1][2]

40

In [8]:
benimMatrixDizim[1,2]

40

In [9]:
benimMatrixDizim[1:,2]

array([40, 60])

In [10]:
benimMatrixDizim[2:,2]

array([60])

In [11]:
yeniListe= [[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]]

In [12]:
yeniListe

[[0, 1, 2, 3, 4],
 [5, 6, 7, 8, 9],
 [10, 11, 12, 13, 14],
 [15, 16, 17, 18, 19],
 [20, 21, 22, 23, 24]]

In [13]:
yeniMatrix = np.array(yeniListe)

In [14]:
yeniMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [16]:
yeniMatrix[[4,2,0]]

array([[20, 21, 22, 23, 24],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4]])

In [17]:
yeniBirDizi = np.arange(5,25)

In [18]:
yeniBirDizi

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [19]:
yeniBirDizi2 = np.random.randint(1,100,20)

In [20]:
yeniBirDizi2

array([32, 59, 76, 10, 80, 65, 77, 95, 21, 79, 54, 14, 39, 74, 46, 31, 84,
       26, 29, 19])

In [21]:
yeniBirDizi2 > 24 

array([ True,  True,  True, False,  True,  True,  True,  True, False,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True, False])

In [22]:
sonuc = yeniBirDizi2 > 24 

In [24]:
sonuc

array([ True,  True,  True, False,  True,  True,  True,  True, False,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True, False])

In [25]:
yeniBirDizi2

array([32, 59, 76, 10, 80, 65, 77, 95, 21, 79, 54, 14, 39, 74, 46, 31, 84,
       26, 29, 19])

In [27]:
yeniBirDizi2[sonuc]

array([32, 59, 76, 80, 65, 77, 95, 79, 54, 39, 74, 46, 31, 84, 26, 29])

In [28]:
sonDizi = np.arange(0,24)

In [29]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [30]:
sonDizi * sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [31]:
sonDizi - sonDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])